version: "3.7"
services:
  apache:
    build:
      context: docker/development/apache
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - php-fpm
  web:
    build:
      context: docker/development/nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./:/app
    depends_on:
      - apache
  php-fpm:
    build:
      context: docker/development/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/app
  php-cli:
    build:
      context: docker/development/php-cli
      dockerfile: Dockerfile
    volumes:
    - ./:/app